### ISSUE TITLE
Failed to load the go-format package

### ISSUE THREAD

**Issue by battlemidget** [lsegal/atom-go-format#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: linux 3.13.0-49-generic
**Thrown From**: [go-format](https://github.com/lsegal/atom-go-format) package, v1.0.7

### Stack Trace

Failed to load the go-format package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/adam/.atom/packages/go-format/lib/go-format-status-view.coffee:4:199)
    at /home/adam/.atom/packages/go-format/lib/go-format-status-view.coffee:9:5
    at Object.<anonymous> (/home/adam/.atom/packages/go-format/lib/go-format-status-view.coffee:41:5)
    at Object.<anonymous> (/home/adam/.atom/packages/go-format/lib/go-format-status-view.coffee:43:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
go-format, v1.0.7
linter, v0.12.1
linter-flake8, v1.4.0
linter-jshint, v0.1.2
linter-pep8, v0.1.0

# Dev
No dev packages
```

**Comment by lsegal** [comment]
Use the great [go-plus](https://github.com/joefitzgerald/go-plus) instead!
