### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

### ISSUE THREAD

**Issue by N0hbdy** [lsegal/atom-go-format#9]
Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [go-format](https://github.com/lsegal/atom-go-format) package, v1.0.7

### Steps To Reproduce

1. Um.  Edit a ruby file and save it?  Not too sure to be honest why its showing up in my ruby editing...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:614

TypeError: Cannot read property 'getScopeDescriptor' of undefined
  at TextEditor.module.exports.TextEditor.scopesAtCursor (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2409:34)
  at TextEditor.module.exports.TextEditor.getCursorScopes (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2414:19)
  at Object.module.exports.format (/Users/amcrae/.atom/packages/go-format/lib/go-format.coffee:45:22)
  at /Users/amcrae/.atom/packages/go-format/lib/go-format.coffee:34:10
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:973:19)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by yoshuawuyts** [comment]
+1, this is super annoying. I've disabled `go-format` until this is resolved.

**Comment by kyoh86** [comment]
+1

**Comment by jpospychala** [comment]
+1

**Comment by jutaz** [comment]
+1

**Comment by monokrome** [comment]
This is a bit odd. It occured after adding a `debugger` statement to a coffee file. I would think that this plugin shouldn't even be doing anything if the file isn't detected as golang.

**Comment by destari** [comment]
This bug makes me want to ram my head into my screen.

**Comment by monokrome** [comment]
Here's hoping @destari's screen had survived theast 72 hours

**Comment by destari** [comment]
Screen's fine, head, not so much!

**Comment by QinMing** [comment]
+1

**Comment by c0rrzin** [comment]
+1

**Comment by monokrome** [comment]
I'm starting to really worry about @destari's screen over here

**Comment by lsegal** [comment]
Use the great [go-plus](https://github.com/joefitzgerald/go-plus) instead!
